ALTER TABLE orders
    ADD COLUMN order_consignment_id VARCHAR(50) NOT NULL,
    ADD COLUMN order_type_id INT,
    ADD COLUMN cod_fee DOUBLE PRECISION NOT NULL,
    ADD COLUMN promo_discount DOUBLE PRECISION NOT NULL,
    ADD COLUMN discount DOUBLE PRECISION NOT NULL,
    ADD COLUMN delivery_fee DOUBLE PRECISION NOT NULL,
    ADD COLUMN order_status VARCHAR(50) NOT NULL,
    ADD COLUMN order_type VARCHAR(50) NOT NULL,
    ADD COLUMN order_amount DOUBLE PRECISION NOT NULL,
    ADD COLUMN total_fee DOUBLE PRECISION NOT NULL;
